/* tslint:disable */
/* eslint-disable */
/**
 * APIView Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  UploadFormData,
  UploadResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    UploadFormDataFromJSON,
    UploadFormDataToJSON,
    UploadResponseFromJSON,
    UploadResponseToJSON,
} from '../models/index';

export interface AutoReviewUploadAutoReviewRequest {
    apiKey: string;
    uploadFormData: UploadFormData;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Upload a source artifact for automatic review
     */
    async autoReviewUploadAutoReviewRaw(requestParameters: AutoReviewUploadAutoReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadResponse>> {
        if (requestParameters['apiKey'] == null) {
            throw new runtime.RequiredError(
                'apiKey',
                'Required parameter "apiKey" was null or undefined when calling autoReviewUploadAutoReview().'
            );
        }

        if (requestParameters['uploadFormData'] == null) {
            throw new runtime.RequiredError(
                'uploadFormData',
                'Required parameter "uploadFormData" was null or undefined when calling autoReviewUploadAutoReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['apiKey'] != null) {
            headerParameters['api-key'] = String(requestParameters['apiKey']);
        }


        let urlPath = `/AutoReview/UploadAutoReview`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UploadFormDataToJSON(requestParameters['uploadFormData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadResponseFromJSON(jsonValue));
    }

    /**
     * Upload a source artifact for automatic review
     */
    async autoReviewUploadAutoReview(requestParameters: AutoReviewUploadAutoReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadResponse> {
        const response = await this.autoReviewUploadAutoReviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
