/* tslint:disable */
/* eslint-disable */
/**
 * APIView Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  UploadResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    UploadResponseFromJSON,
    UploadResponseToJSON,
} from '../models/index';

export interface AutoReviewUploadAutoReviewRequest {
    apiKey: string;
    file: Blob;
    label: string;
    packageVersion: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Upload a source artifact for automatic review
     */
    async autoReviewUploadAutoReviewRaw(requestParameters: AutoReviewUploadAutoReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadResponse>> {
        if (requestParameters['apiKey'] == null) {
            throw new runtime.RequiredError(
                'apiKey',
                'Required parameter "apiKey" was null or undefined when calling autoReviewUploadAutoReview().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling autoReviewUploadAutoReview().'
            );
        }

        if (requestParameters['label'] == null) {
            throw new runtime.RequiredError(
                'label',
                'Required parameter "label" was null or undefined when calling autoReviewUploadAutoReview().'
            );
        }

        if (requestParameters['packageVersion'] == null) {
            throw new runtime.RequiredError(
                'packageVersion',
                'Required parameter "packageVersion" was null or undefined when calling autoReviewUploadAutoReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['apiKey'] != null) {
            headerParameters['api-key'] = String(requestParameters['apiKey']);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['label'] != null) {
            formParams.append('label', requestParameters['label'] as any);
        }

        if (requestParameters['packageVersion'] != null) {
            formParams.append('packageVersion', requestParameters['packageVersion'] as any);
        }


        let urlPath = `/AutoReview/UploadAutoReview`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadResponseFromJSON(jsonValue));
    }

    /**
     * Upload a source artifact for automatic review
     */
    async autoReviewUploadAutoReview(requestParameters: AutoReviewUploadAutoReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadResponse> {
        const response = await this.autoReviewUploadAutoReviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
