/* tslint:disable */
/* eslint-disable */
/**
 * APIView Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFormData
 */
export interface UploadFormData {
    /**
     * 
     * @type {Blob}
     * @memberof UploadFormData
     */
    file: Blob;
    /**
     * 
     * @type {string}
     * @memberof UploadFormData
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFormData
     */
    packageVersion: string;
}

/**
 * Check if a given object implements the UploadFormData interface.
 */
export function instanceOfUploadFormData(value: object): value is UploadFormData {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('packageVersion' in value) || value['packageVersion'] === undefined) return false;
    return true;
}

export function UploadFormDataFromJSON(json: any): UploadFormData {
    return UploadFormDataFromJSONTyped(json, false);
}

export function UploadFormDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFormData {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'label': json['label'],
        'packageVersion': json['packageVersion'],
    };
}

export function UploadFormDataToJSON(json: any): UploadFormData {
    return UploadFormDataToJSONTyped(json, false);
}

export function UploadFormDataToJSONTyped(value?: UploadFormData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
        'label': value['label'],
        'packageVersion': value['packageVersion'],
    };
}

