emit:
  - "@azure-tools/typespec-ts"
options:
  "@azure-tools/typespec-ts":
    packageDetails:
      name: "@api-view/typescript-client"
      version: "1.0.0"
    generateMetadata: true
    generateTest: false
    emitterOutputDir: "{project-root}/../packages/typescript-client"
